language: node_js
node_js:
  - 'node'
  - 'lts/*'
cache: yarn
install:
  - yarn install
  - yarn link
  - cd example
  - yarn link react-native-particles-webgl
  - yarn install
script:
  - yarn test
  - yarn build
branches:
  only: master
notifications:
  email: false
